events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Local CDN Cache Storage inside the container
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cdn_cache:10m max_size=1g inactive=60m use_temp_path=off;

    # Explicitly define what makes a cache key unique
    proxy_cache_key "$scheme$request_method$host$request_uri";

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html; # mount dist/client here
        # Visual indicator for students to see CDN activity
        add_header X-Cache-Status $upstream_cache_status always;

        # Tanstack Start's hashed assets — filenames are content-hashed, so cache hard
        location /assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
            add_header X-Cache-Status $upstream_cache_status always;
        }

        # favicons live at the root of output/public
        location = /favicon.svg {
            expires 30d;
        }

        location = /favicon.ico {
            expires 30d;
        }

        # TanStack Start Build-Time Router Assets & Static Server Function Cache
        # Served directly from /usr/share/nginx/html/__tsr/
        location /__tsr/ {
            expires 30d;
            add_header Cache-Control "public, immutable";
            try_files $uri =404;
        }

        # Dynamic Server Functions (Runtime RPCs)
        # Proxy directly to the Node.js / TanStack Start server
        # location /_serverFn/ {
        #     proxy_pass http://delay-proxy:3001;

        #     proxy_cache cdn_cache;
        #     proxy_cache_bypass 1; # never serve this from cache
        #     proxy_no_cache 1; # never store this in cache
        #     proxy_set_header Host $http_host; # not $host because it strips the port.
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # }
        # Everything else → Tanstack Start SSR server (no caching, just proxy)
        location / {
            proxy_pass http://delay-proxy:3001;

            # See README.md for why we ignore these headers. In short, Tanstack Start's SSR server is sending them, but they don't make sense for a CDN cache.
            proxy_ignore_headers Cache-Control Expires;

            proxy_cache cdn_cache;
            proxy_cache_bypass 1; # never serve this from cache
            proxy_no_cache 1; # never store this in cache

            proxy_set_header Host $http_host; # not $host because it strips the port.
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}