events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Local CDN Cache Storage inside the container
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cdn_cache:10m max_size=1g inactive=60m use_temp_path=off;

    # Explicitly define what makes a cache key unique
    proxy_cache_key "$scheme$request_method$host$request_uri";

    server {
        listen 80;
        server_name localhost;

        # The root directory for the application files
        root /var/www/app;

        # Visual indicator for students to see CDN activity
        # add_header X-Cache-Status $upstream_cache_status always;

        # Use ^~ to take precedence over the regex match below
        location ^~ /assets/ {
            try_files $uri =404;
            expires 1y;
            add_header Cache-Control "public, immutable";
            add_header X-Cache-Status "HIT-LOCAL-ASSET-FOLDER" always;
        }

        location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf)$ {
            try_files $uri =404;
            expires 7d;
            add_header Cache-Control "public, no-cache, must-revalidate" always;
            add_header X-Cache-Status "HIT-LOCAL-PUBLIC-FOLDER" always;
        }

        # TanStack Start Build-Time Router Assets & Static Server Function Cache
        # Served directly from /usr/share/nginx/html/__tsr/
        # Add ^~ to override regex matching for build-time router assets
        location ^~ /__tsr/ {
            try_files $uri =404;
            expires 30d;
            add_header Cache-Control "public, immutable";
            add_header X-Cache-Status "HIT-LOCAL-TSR-FOLDER" always;
        }

        # Everything else → Tanstack Start SSR server (no caching, just proxy)
        location / {
            proxy_pass http://delay-proxy:3001;

            # This is not necessary. Leave it here just to make it clear that we are not caching SSR responses.
            proxy_cache cdn_cache;
            proxy_cache_bypass 1; # never serve this from cache
            proxy_no_cache 1; # never store this in cache

            # Pass the original request headers to the SSR server
            proxy_set_header Host $http_host; # not $host because it strips the port.
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Optional indicator showing it passed through to the SSR origin directly
            add_header X-Cache-Status "DYNAMIC-SSR-BYPASS" always;

        }
    }
}