/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Ssr_awaitedRouteImport } from './routes/ssr_awaited'
import { Route as Ssr_awaited_prerenderedRouteImport } from './routes/ssr_awaited_prerendered'
import { Route as Ssr_prerenderedRouteImport } from './routes/ssr_prerendered'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Ssr_awaitedRoute = Ssr_awaitedRouteImport.update({
  id: '/ssr_awaited',
  path: '/ssr_awaited',
  getParentRoute: () => rootRouteImport,
} as any)
const Ssr_awaited_prerenderedRoute = Ssr_awaited_prerenderedRouteImport.update({
  id: '/ssr_awaited_prerendered',
  path: '/ssr_awaited_prerendered',
  getParentRoute: () => rootRouteImport,
} as any)
const Ssr_prerenderedRoute = Ssr_prerenderedRouteImport.update({
  id: '/ssr_prerendered',
  path: '/ssr_prerendered',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ssr_awaited': typeof Ssr_awaitedRoute
  '/ssr_awaited_prerendered': typeof Ssr_awaited_prerenderedRoute
  '/ssr_prerendered': typeof Ssr_prerenderedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ssr_awaited': typeof Ssr_awaitedRoute
  '/ssr_awaited_prerendered': typeof Ssr_awaited_prerenderedRoute
  '/ssr_prerendered': typeof Ssr_prerenderedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ssr_awaited': typeof Ssr_awaitedRoute
  '/ssr_awaited_prerendered': typeof Ssr_awaited_prerenderedRoute
  '/ssr_prerendered': typeof Ssr_prerenderedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ssr_awaited' | '/ssr_awaited_prerendered' | '/ssr_prerendered'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ssr_awaited' | '/ssr_awaited_prerendered' | '/ssr_prerendered'
  id:
    | '__root__'
    | '/'
    | '/ssr_awaited'
    | '/ssr_awaited_prerendered'
    | '/ssr_prerendered'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Ssr_awaitedRoute: typeof Ssr_awaitedRoute
  Ssr_awaited_prerenderedRoute: typeof Ssr_awaited_prerenderedRoute
  Ssr_prerenderedRoute: typeof Ssr_prerenderedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr_awaited': {
      id: '/ssr_awaited'
      path: '/ssr_awaited'
      fullPath: '/ssr_awaited'
      preLoaderRoute: typeof Ssr_awaitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr_awaited_prerendered': {
      id: '/ssr_awaited_prerendered'
      path: '/ssr_awaited_prerendered'
      fullPath: '/ssr_awaited_prerendered'
      preLoaderRoute: typeof Ssr_awaited_prerenderedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr_prerendered': {
      id: '/ssr_prerendered'
      path: '/ssr_prerendered'
      fullPath: '/ssr_prerendered'
      preLoaderRoute: typeof Ssr_prerenderedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Ssr_awaitedRoute: Ssr_awaitedRoute,
  Ssr_awaited_prerenderedRoute: Ssr_awaited_prerenderedRoute,
  Ssr_prerenderedRoute: Ssr_prerenderedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
